return {
	filetypes = {
		"astro",
		"astro-markdown",
		"django-html",
		"gohtml",
		"handlebars",
		"hbs",
		"html",
		"liquid",
		"php",
		"css",
		"less",
		"postcss",
		"sass",
		"scss",
		"js",
		"jsx",
		"javascript",
		"javascriptreact",
		"typescript",
		"typescriptreact",
		"vue",
		"svelte",
	},
	settings = {
		ailwindCSS = {
			classAttributes = { "class", "className", "classList", "ngClass" },
			lint = {
				cssConflict = "warning",
				invalidApply = "error",
				invalidConfigPath = "error",
				invalidScreen = "error",
				invalidTailwindDirective = "error",
				invalidVariant = "error",
				recommendedVariantOrder = "warning",
			},
			validate = true,
		},
	},
}
