#!/usr/bin/env sh

# you must configure sudo such that it will be able to run the command without password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0

# WITH SIP ENABLED (Installed Limelight seperately, Don't need this)
yabai -m config window_border                off

# WITH SIP DISABLED (Limelight build into Yabai, enable it here)
# yabai -m config window_border                on
# yabai -m config window_border_width          6
# yabai -m config active_window_border_color   0xff7aa2f7
# yabai -m config normal_window_border_color   0xff444b6a
# yabai -m config insert_feedback_color        0xff61afef

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier               ctrl
# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1                move
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  28 
yabai -m config bottom_padding               2
yabai -m config left_padding                 2
yabai -m config right_padding                2
yabai -m config window_gap                   10

yabai -m space 1 --label I
yabai -m space 2 --label II
yabai -m space 3 --label III
yabai -m space 4 --label IV
yabai -m space 5 --label V
yabai -m space 6 --label VI
yabai -m space 7 --label VII
yabai -m space 8 --label VIII
yabai -m space 9 --label IX
yabai -m space 10 --label X

# yabai -m rule --add app="Google Chrome" space=1
# yabai -m rule --add app="Alacritty"     space=2
# ^^ these are annoying
# yabai -m rule --add app="Safari"        space=3
# yabai -m rule --add app="Zoom"          space=4
# yabai -m rule --add app="Discord"       space=5

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Font Book$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add title="mylauncher" sticky=on layer=above border=off manage=off

# SPACEBAR_HEIGHT=$(spacebar -m config height)
# yabai -m config external_bar all:$SPACEBAR_HEIGHT:0

# kill any existing limelight process if one exists, before we launch a new one
killall limelight &> /dev/null
limelight &> /dev/null &

echo "yabai configuration loaded.."
